# Stage 1: Build Node.js application
FROM node:20.12.2 AS nodejs-build
RUN apt-get update -y

# Copy the rest of the application code to the working directory
COPY ./marketplace/game-ui-app/ ./market/

# Expose any ports the app needs
EXPOSE 3000

# Command to run the application

WORKDIR /market
RUN npm i
CMD ["npm", "run", "dev"]
